[package]
name = "rpp_cli"
version = "0.1.0"
authors = ["Ed Cragg <ed.cragg@eipi.xyz>"]
edition = "2018"

[[bin]]
name = "rpp"
path = "src/main.rs"

[dependencies]
rpp = { version = "0.1.0", path = ".." }
structopt = "0.3.21"
humansize = "1.1.0"
humantime = "2.0.1"
